- name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        key_path: ""
        script: |
          cd /home/ec2-user
          if [ -d "devops_portfolio" ]; then
            cd devops_portfolio
            git pull origin main
          else
            git clone https://github.com/kowshikaarumugam/devops_portfolio.git
            cd devops_portfolio
          fi
          docker stop portfolio-app || true
          docker rm portfolio-app || true
          docker build -t devops-portfolio .
          docker run -d -p 5000:5000 --name portfolio-app devops-portfolio
          echo "Deployment successful!"